sudo: false

services:
  - docker
  
env:
  global:
  - secure: "MhcV5a3N8vrJ68sLcqQkH9F/gN2r2ibNM2y7yrt+mJ9N5WLl9bdzIEWyUD4AAwBk6Rf9BTQ25utpbWIlPLo2rwChh4yldGA/PQF3IJju4nlJLuVjX9XPk9PEZLYbwQGumMiRb0TonwvNNG5SyrM+mu/YT3oDKwykLtTG4lz3p14="
  - secure: "CqpA+9sezpt3BXRuocToa9dDTOMEpg08XCy9WX73PbfoDHFEPXSEboY46VhbX4p3KJeRZ2Go5zQS5pPB7+CubMMKmb1xmo1pnHtmWemnnfHzSRPEM27wMokNkYLY8jIRcZkdJpZHWjGWV4fzr6cDMg3t22gzOB+eUnGCLa7Ziqo="
language: c
compiler: gcc


before_install:
- pip install --user awscli
- docker pull intrigus/docker-raspberry-pi-cross-compiler
- docker run intrigus/docker-raspberry-pi-cross-compiler > ~/bin/rpxc
- chmod +x ~/bin/rpxc
- export PATH=$PATH:$HOME/bin:$HOME/.local/bin
- export RPXC_IMAGE=intrigus/docker-raspberry-pi-cross-compiler

script:
- echo "PKG_CONFIG_DIR=" >> .lwjgl_env_rpxc
- echo "PKG_CONFIG_LIBDIR=${LWJGL_BUILD_SYSROOT}/usr/lib/pkgconfig:${LWJGL_BUILD_SYSROOT}/usr/share/pkgconfig:${LWJGL_BUILD_SYSROOT}/usr/lib/arm-linux-gnueabihf/pkgconfig:${LWJGL_BUILD_SYSROOT}/usr/share/arm-linux-gnueabihf/pkgconfig" >> .lwjgl_env_rpxc
- echo "PKG_CONFIG_SYSROOT_DIR=${LWJGL_BUILD_SYSROOT}" >> .lwjgl_env_rpxc
- mkdir build
- echo 'cd build' >> tempScript.sh
- echo 'CC="arm-linux-gnueabihf-gcc" cmake -DCMAKE_LIBRARY_PATH=${SYSROOT} -DBUILD_SHARED_LIBS=ON -DGLFW_BUILD_EXAMPLES=OFF -DGLFW_BUILD_TESTS=OFF -DGLFW_BUILD_DOCS=OFF -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_FLAGS="-U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=0" ..' >> tempScript.sh
- echo 'cmake --build .' >> tempScript.sh
- echo 'cd src' >> tempScript.sh
- echo 'arm-linux-gnueabihf-strip libglfw.so' >> tempScript.sh
- chmod +x tempScript.sh
- rpxc --args "--env-file .lwjgl_env_rpxc" bash -c './tempScript.sh' 
#- "aws s3 cp libglfw.so s3://build.lwjgl.org/nightly/linux/x64/ --acl public-read --storage-class REDUCED_REDUNDANCY --cache-control \"public, must-revalidate, proxy-revalidate, max-age=0\""
#- "git log --pretty=format:%H HEAD~2..HEAD~1 | head -n 1 > revision.git"
#- "aws s3 cp revision.git s3://build.lwjgl.org/nightly/linux/x64/libglfw.so.git --acl public-read --storage-class REDUCED_REDUNDANCY --cache-control \"public, must-revalidate, proxy-revalidate, max-age=0\""
